# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql  
      - mysqldbvolume:/var/lib/mysql
    ports: 
      - 3306:3306
    networks:
      - fishy-network

  fishy-api:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - 3000:8080
    restart: always
    depends_on:
      - db
    networks:
      - fishy-network

networks:
  fishy-network:
    driver: bridge

# Volumes
volumes:
  mysqldbvolume:
    driver: local